sudo: false
language: python
cache: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
  - nightly
  - pypy

matrix:
  fast_finish: true
  allow_failures:
  - python: 3.7-dev
  - python: nightly
  - python: pypy
  include:
  - os: osx
    language: generic

before_install: if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source .travis-osx; fi
install: pip install --pre -U tox
script: tox -e py
after_success:
  - tox -e coverage
  - tox -e codecov
